/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    FooterMenu: typeof import('./src/components/FooterMenu.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    HomeButton: typeof import('./src/components/HomeButton.vue')['default']
    HomeFooter: typeof import('./src/components/HomeFooter.vue')['default']
    HomeHeader: typeof import('./src/components/HomeHeader.vue')['default']
    Menubar: typeof import('./src/components/ui/menubar/Menubar.vue')['default']
    MenubarCheckboxItem: typeof import('./src/components/ui/menubar/MenubarCheckboxItem.vue')['default']
    MenubarContent: typeof import('./src/components/ui/menubar/MenubarContent.vue')['default']
    MenubarGroup: typeof import('./src/components/ui/menubar/MenubarGroup.vue')['default']
    MenubarItem: typeof import('./src/components/ui/menubar/MenubarItem.vue')['default']
    MenubarLabel: typeof import('./src/components/ui/menubar/MenubarLabel.vue')['default']
    MenubarMenu: typeof import('./src/components/ui/menubar/MenubarMenu.vue')['default']
    MenubarRadioGroup: typeof import('./src/components/ui/menubar/MenubarRadioGroup.vue')['default']
    MenubarRadioItem: typeof import('./src/components/ui/menubar/MenubarRadioItem.vue')['default']
    MenubarSeparator: typeof import('./src/components/ui/menubar/MenubarSeparator.vue')['default']
    MenubarShortcut: typeof import('./src/components/ui/menubar/MenubarShortcut.vue')['default']
    MenubarSub: typeof import('./src/components/ui/menubar/MenubarSub.vue')['default']
    MenubarSubContent: typeof import('./src/components/ui/menubar/MenubarSubContent.vue')['default']
    MenubarSubTrigger: typeof import('./src/components/ui/menubar/MenubarSubTrigger.vue')['default']
    MenubarTrigger: typeof import('./src/components/ui/menubar/MenubarTrigger.vue')['default']
    NavigationMenu: typeof import('./src/components/ui/navigation-menu/NavigationMenu.vue')['default']
    NavigationMenuContent: typeof import('./src/components/ui/navigation-menu/NavigationMenuContent.vue')['default']
    NavigationMenuIndicator: typeof import('./src/components/ui/navigation-menu/NavigationMenuIndicator.vue')['default']
    NavigationMenuItem: typeof import('./src/components/ui/navigation-menu/NavigationMenuItem.vue')['default']
    NavigationMenuLink: typeof import('./src/components/ui/navigation-menu/NavigationMenuLink.vue')['default']
    NavigationMenuList: typeof import('./src/components/ui/navigation-menu/NavigationMenuList.vue')['default']
    NavigationMenuTrigger: typeof import('./src/components/ui/navigation-menu/NavigationMenuTrigger.vue')['default']
    NavigationMenuViewport: typeof import('./src/components/ui/navigation-menu/NavigationMenuViewport.vue')['default']
    NewMap: typeof import('./src/components/NewMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sheet: typeof import('./src/components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./src/components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./src/components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./src/components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./src/components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./src/components/ui/sheet/SheetHeader.vue')['default']
    SheetOverlay: typeof import('./src/components/ui/sheet/SheetOverlay.vue')['default']
    SheetTitle: typeof import('./src/components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./src/components/ui/sheet/SheetTrigger.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
