services:
  mosquitto:
    image: docker.io/library/eclipse-mosquitto:openssl
    container_name: iot_mosquitto
    restart: unless-stopped
    networks:
      - iot_net
    ports:
      - "1883:1883"
      - "8083:8083"
    environment:
      - MOSQUITTO_CHANGE_OWNER=0
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config/mosquitto.passwd:/mosquitto/config/mosquitto.passwd:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  postgres:
    image: docker.io/library/postgres:17-alpine
    container_name: iot_postgres
    restart: unless-stopped
    networks:
      - iot_net
    environment:
      POSTGRES_DB: iot_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Shanghai
      LANG: zh_CN.UTF-8
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=zh_CN.UTF-8 --lc-ctype=zh_CN.UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d iot_manager_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: docker.io/library/mongo:latest
    container_name: iot_mongo
    restart: unless-stopped
    networks:
      - iot_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    command:
      [
        "mongod",
        "--quiet",
        "--logpath",
        "/dev/null",
        "--setParameter",
        "logLevel=0",
      ]

  api-gateway:
    image: ghcr.io/xiaozhuabcd1234/iot-manage-system_api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: iot_api-gateway
    restart: unless-stopped
    networks:
      - iot_net
    environment:
      USER_SERVICE_URL: "user-service:8001"
      MARK_SERVICE_URL: "mark-service:8004"
      MQTT_SERVICE_URL: "mqtt-watch:8003"
      JWT_SECRET: "your-secret-key"
      HTTP_PROXY: ""
      http_proxy: ""
      HTTPS_PROXY: ""
      https_proxy: ""
      FTP_PROXY: ""
      ftp_proxy: ""
      ALL_PROXY: ""
      all_proxy: ""
      NO_PROXY: ""
      no_proxy: ""
    ports:
      - "8000:8000"

  user-service:
    image: ghcr.io/xiaozhuabcd1234/iot-manage-system_user-service:latest
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: iot_user-service
    restart: unless-stopped
    networks:
      - iot_net
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: iot_manager_db
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: "your-secret-key"
      TZ: Asia/Shanghai
      ADMIN_NAME: admin
      ADMIN_PWD: admin
    # ports:
    #   - "8001:8001"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8081/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  mqtt-watch:
    image: ghcr.io/xiaozhuabcd1234/iot-manage-system_mqtt-watch:latest
    build:
      context: ./mqtt-watch
      dockerfile: Dockerfile
    container_name: iot_mqtt-watch
    restart: unless-stopped
    networks:
      - iot_net
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: iot_manager_db
      DB_USER: postgres
      DB_PASSWORD: password

      # ---------- MongoDB ----------
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_DB: mqtt_db

      # ---------- MQTT ----------
      MQTT_BROKER: ws://mosquitto:8083
      MQTT_USERNAME: admin
      MQTT_PASSWORD: admin
    # ports:
    #   - "8003:8003"

  mark-service:
    image: ghcr.io/xiaozhuabcd1234/iot-manage-system_mark-service:latest
    build:
      context: ./mark-service
      dockerfile: Dockerfile
    container_name: iot_mark-service
    restart: unless-stopped
    networks:
      - iot_net
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: iot_manager_db
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: "your-secret-key"
      TZ: Asia/Shanghai
    # ports:
    #   - "8004:8004"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8004/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    image: ghcr.io/xiaozhuabcd1234/iot-manage-system_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: # 对应 Dockerfile 里的 ARG
        VITE_AMAP_KEY: ${VITE_AMAP_KEY}
        VITE_AMAP_SECURITY_CODE: ${VITE_AMAP_SECURITY_CODE}
        VITE_MQTT_URL: ${VITE_MQTT_URL}
    container_name: iot_frontend
    restart: unless-stopped
    networks:
      - iot_net
    ports:
      - "3000:80"

volumes:
  mosquitto_data:
  mosquitto_log:
  postgres_data:
  mongo_data:

networks:
  iot_net:
    driver: bridge
