# 需要先编译前端代码
### 编译前端代码

# ```bash
# cd ./frontend
# npm install
# npm run build
# cp -r dist ../backend
# ```

## 编译完成后再构建
FROM ghcr.io/astral-sh/uv:python3.13-alpine

WORKDIR /app

RUN apk add --no-cache gcc python3-dev musl-dev linux-headers

COPY backend/. /app

RUN uv sync

EXPOSE 8000

CMD ["uv","run","fastapi","run", "main.py", "--host", "0.0.0.0", "--port", "8000"]
