FROM ghcr.io/astral-sh/uv:python3.13-alpine

WORKDIR /app

# 安装系统依赖
RUN apk add --no-cache gcc python3-dev musl-dev linux-headers

# 先复制依赖声明文件
COPY backend/pyproject.toml \
    backend/requirements.txt \
    backend/uv.lock \
    /app/

RUN uv sync --default-index https://pypi.tuna.tsinghua.edu.cn/simple

COPY backend/. /app

EXPOSE 8000

CMD ["uv","run","fastapi","run", "main.py", "--host", "0.0.0.0", "--port", "8000"]
