name: 自动化部署
on:
  push:
    branches: [main]

env:
  SERVER_PATH: ~/IOT-Management-System

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 构建并复制前端
        run: |
          cd frontend
          npm install
          npm run build
          cp -r ./dist ../backend/

      - name: 打包文件
        run: |
          tar -czvf deploy-pkg.tar.gz \
            backend \
            forwarder \
            docker-compose.yml \

      - name: 上传文件
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: deploy-pkg.tar.gz
          target: ${{ env.SERVER_PATH }}

      - name: 远程构建并部署
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{env.SERVER_PATH}}
            ls -la  # 检查当前目录文件
            if [ -f "deploy-pkg.tar.gz" ]; then
              echo "文件存在，开始解压"
              tar -xzvf deploy-pkg.tar.gz
            else
              echo "错误：deploy-pkg.tar.gz 文件不存在"
              exit 1
            fi
            if [ -f "docker-compose.yml" ]; then
              echo "docker-compose.yml 存在，开始部署"
              docker-compose up --build -d
            else
              echo "错误：docker-compose.yml 文件不存在"
              exit 1
            fi
